dist: xenial
language: python
python: "3.7"

install:
  - pip3 install -r requirements.txt --upgrade
  - pip3 install flake8~=3.6.0 pytest --upgrade
  - pip3 uninstall pytest-capturelog || true
script:
  - flake8

cache:
  directories:
    - $HOME/virtualenv/python3.7.*
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http
after_success:
  - echo Placeholder
